name: Cotação do Dólar

# Defina quando o workflow será acionado. O cron job abaixo é configurado para rodar a cada 5 minutos de segunda a sexta-feira.
on:
  schedule:
    - cron: "*/5 * * * 1-5"  # Executa a cada 5 minutos de segunda a sexta-feira

jobs:
  executar-script:
    runs-on: ubuntu-latest  # O trabalho será executado em uma máquina virtual do GitHub

    steps:
      # Passo 1: Clonar o repositório
      - name: Clonar repositório
        uses: actions/checkout@v3

      # Passo 2: Configurar o ambiente Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  # Você pode especificar a versão do Python, por exemplo, 3.8 ou 3.9

      # Passo 3: Instalar dependências (requests, openpyxl, etc.)
      - name: Instalar dependências
        run: pip install requests openpyxl  # Instalar as bibliotecas necessárias para o script

      # Passo 4: Executar o script Python
      - name: Executar script
        run: python seu_script.py  # Executa o script Python que você subiu
